#include <stdio.h>
#define CLEKS_IMPLEMENTATION
#include "../cleks2.h"

typedef enum{
    HTML_HTML,
    HTML_HEAD,
    HTML_BODY,
    HTML_META,
    HTML_DIV,
    HTML_TITLE,
    HTML_SCRIPT,
    HTML_STYLE,
    HTML_LI,
    HTML_UL,
    HTML_A,
    HTML_P,
    HTML_STRONG,
    HTML_H1,
    HTML_H2,
    HTML_H3,
    HTML_H4,
    HTML_H5,
    HTML_H6,
    HTML_IMG,
    HTML_SPAN,
    HTML_TABLE,
    HTML_TR,
    HTML_TD,
    HTML_TH,
    HTML_TBODY,
    HTML_THEAD,
    HTML_TFOOT,
    HTML_FORM,
    HTML_INPUT,
    HTML_BUTTON,
    HTML_LABEL,
    HTML_SELECT,
    HTML_OPTION,
    HTML_TEXTAREA,
    HTML_IFRAME,
    HTML_NAV,
    HTML_SECTION,
    HTML_HEADER,
    HTML_FOOTER,
    HTML_ARTICLE,
    HTML_ASIDE,
    HTML_CANVAS,
    HTML_VIDEO,
    HTML_AUDIO,
    HTML_SOURCE,
    HTML_TRACK,
    HTML_EMBED,
    HTML_OBJECT,
    HTML_PARAM,
    HTML_BLOCKQUOTE,
    HTML_CITE,
    HTML_CODE,
    HTML_PRE,
    HTML_OL,
    HTML_BR,
    HTML_HR,
    HTML_B,
    HTML_I,
    HTML_U,
    HTML_SMALL,
    HTML_SUB,
    HTML_SUP,
    HTML_INS,
    HTML_DEL,
    HTML_MARK,
    HTML_Q,
    HTML_DATA,
    HTML_TIME,
    HTML_OUTPUT,
    HTML_PROGRESS,
    HTML_METER,

    HTML_HTML_END,
    HTML_HEAD_END,
    HTML_BODY_END,
    HTML_META_END,
    HTML_DIV_END,
    HTML_TITLE_END,
    HTML_SCRIPT_END,
    HTML_STYLE_END,
    HTML_LI_END,
    HTML_UL_END,
    HTML_A_END,
    HTML_P_END,
    HTML_STRONG_END,
    HTML_H1_END,
    HTML_H2_END,
    HTML_H3_END,
    HTML_H4_END,
    HTML_H5_END,
    HTML_H6_END,
    HTML_IMG_END,
    HTML_SPAN_END,
    HTML_TABLE_END,
    HTML_TR_END,
    HTML_TD_END,
    HTML_TH_END,
    HTML_TBODY_END,
    HTML_THEAD_END,
    HTML_TFOOT_END,
    HTML_FORM_END,
    HTML_INPUT_END,
    HTML_BUTTON_END,
    HTML_LABEL_END,
    HTML_SELECT_END,
    HTML_OPTION_END,
    HTML_TEXTAREA_END,
    HTML_IFRAME_END,
    HTML_NAV_END,
    HTML_SECTION_END,
    HTML_HEADER_END,
    HTML_FOOTER_END,
    HTML_ARTICLE_END,
    HTML_ASIDE_END,
    HTML_CANVAS_END,
    HTML_VIDEO_END,
    HTML_AUDIO_END,
    HTML_SOURCE_END,
    HTML_TRACK_END,
    HTML_EMBED_END,
    HTML_OBJECT_END,
    HTML_PARAM_END,
    HTML_BLOCKQUOTE_END,
    HTML_CITE_END,
    HTML_CODE_END,
    HTML_PRE_END,
    HTML_OL_END,
    HTML_BR_END,
    HTML_HR_END,
    HTML_B_END,
    HTML_I_END,
    HTML_U_END,
    HTML_SMALL_END,
    HTML_SUB_END,
    HTML_SUP_END,
    HTML_INS_END,
    HTML_DEL_END,
    HTML_MARK_END,
    HTML_Q_END,
    HTML_DATA_END,
    HTML_TIME_END,
    HTML_OUTPUT_END,
    HTML_PROGRESS_END,
    HTML_METER_END,
    HTML_END,
    HTML_UNKNOWN
} HtmlField;

CleksField html_fields[] = {
    [HTML_HTML] = {"<html", ">"},
    [HTML_HEAD] = {"<head", ">"},
    [HTML_BODY] = {"<body", ">"},
    [HTML_META] = {"<meta", ">"},
    [HTML_DIV] = {"<div", ">"},
    [HTML_TITLE] = {"<title", ">"},
    [HTML_SCRIPT] = {"<script", ">"},
    [HTML_STYLE] = {"<style", ">"},
    [HTML_LI] = {"<li", ">"},
    [HTML_UL] = {"<ul", ">"},
    [HTML_A] = {"<a", ">"},
    [HTML_P] = {"<p", ">"},
    [HTML_STRONG] = {"<strong", ">"},
    [HTML_H1] = {"<h1", ">"},
    [HTML_H2] = {"<h2", ">"},
    [HTML_H3] = {"<h3", ">"},
    [HTML_H4] = {"<h4", ">"},
    [HTML_H5] = {"<h5", ">"},
    [HTML_H6] = {"<h6", ">"},
    [HTML_IMG] = {"<img", ">"},
    [HTML_SPAN] = {"<span", ">"},
    [HTML_TABLE] = {"<table", ">"},
    [HTML_TR] = {"<tr", ">"},
    [HTML_TD] = {"<td", ">"},
    [HTML_TH] = {"<th", ">"},
    [HTML_TBODY] = {"<tbody", ">"},
    [HTML_THEAD] = {"<thead", ">"},
    [HTML_TFOOT] = {"<tfoot", ">"},
    [HTML_FORM] = {"<form", ">"},
    [HTML_INPUT] = {"<input", ">"},
    [HTML_BUTTON] = {"<button", ">"},
    [HTML_LABEL] = {"<label", ">"},
    [HTML_SELECT] = {"<select", ">"},
    [HTML_OPTION] = {"<option", ">"},
    [HTML_TEXTAREA] = {"<textarea", ">"},
    [HTML_IFRAME] = {"<iframe", ">"},
    [HTML_NAV] = {"<nav", ">"},
    [HTML_SECTION] = {"<section", ">"},
    [HTML_HEADER] = {"<header", ">"},
    [HTML_FOOTER] = {"<footer", ">"},
    [HTML_ARTICLE] = {"<article", ">"},
    [HTML_ASIDE] = {"<aside", ">"},
    [HTML_CANVAS] = {"<canvas", ">"},
    [HTML_VIDEO] = {"<video", ">"},
    [HTML_AUDIO] = {"<audio", ">"},
    [HTML_SOURCE] = {"<source", ">"},
    [HTML_TRACK] = {"<track", ">"},
    [HTML_EMBED] = {"<embed", ">"},
    [HTML_OBJECT] = {"<object", ">"},
    [HTML_PARAM] = {"<param", ">"},
    [HTML_BLOCKQUOTE] = {"<blockquote", ">"},
    [HTML_CITE] = {"<cite", ">"},
    [HTML_CODE] = {"<code", ">"},
    [HTML_PRE] = {"<pre", ">"},
    [HTML_OL] = {"<ol", ">"},
    [HTML_BR] = {"<br", ">"},
    [HTML_HR] = {"<hr", ">"},
    [HTML_B] = {"<b", ">"},
    [HTML_I] = {"<i", ">"},
    [HTML_U] = {"<u", ">"},
    [HTML_SMALL] = {"<small", ">"},
    [HTML_SUB] = {"<sub", ">"},
    [HTML_SUP] = {"<sup", ">"},
    [HTML_INS] = {"<ins", ">"},
    [HTML_DEL] = {"<del", ">"},
    [HTML_MARK] = {"<mark", ">"},
    [HTML_Q] = {"<q", ">"},
    [HTML_DATA] = {"<data", ">"},
    [HTML_TIME] = {"<time", ">"},
    [HTML_OUTPUT] = {"<output", ">"},
    [HTML_PROGRESS] = {"<progress", ">"},
    [HTML_METER] = {"<meter", ">"},

    [HTML_HTML_END] = {"</html", ">"},
    [HTML_HEAD_END] = {"</head", ">"},
    [HTML_BODY_END] = {"</body", ">"},
    [HTML_META_END] = {"</meta", ">"},
    [HTML_DIV_END] = {"</div", ">"},
    [HTML_TITLE_END] = {"</title", ">"},
    [HTML_SCRIPT_END] = {"</script", ">"},
    [HTML_STYLE_END] = {"</style", ">"},
    [HTML_LI_END] = {"</li", ">"},
    [HTML_UL_END] = {"</ul", ">"},
    [HTML_A_END] = {"</a", ">"},
    [HTML_P_END] = {"</p", ">"},
    [HTML_STRONG_END] = {"</strong", ">"},
    [HTML_H1_END] = {"</h1", ">"},
    [HTML_H2_END] = {"</h2", ">"},
    [HTML_H3_END] = {"</h3", ">"},
    [HTML_H4_END] = {"</h4", ">"},
    [HTML_H5_END] = {"</h5", ">"},
    [HTML_H6_END] = {"</h6", ">"},
    [HTML_IMG_END] = {"</img", ">"},
    [HTML_SPAN_END] = {"</span", ">"},
    [HTML_TABLE_END] = {"</table", ">"},
    [HTML_TR_END] = {"</tr", ">"},
    [HTML_TD_END] = {"</td", ">"},
    [HTML_TH_END] = {"</th", ">"},
    [HTML_TBODY_END] = {"</tbody", ">"},
    [HTML_THEAD_END] = {"</thead", ">"},
    [HTML_TFOOT_END] = {"</tfoot", ">"},
    [HTML_FORM_END] = {"</form", ">"},
    [HTML_INPUT_END] = {"</input", ">"},
    [HTML_BUTTON_END] = {"</button", ">"},
    [HTML_LABEL_END] = {"</label", ">"},
    [HTML_SELECT_END] = {"</select", ">"},
    [HTML_OPTION_END] = {"</option", ">"},
    [HTML_TEXTAREA_END] = {"</textarea", ">"},
    [HTML_IFRAME_END] = {"</iframe", ">"},
    [HTML_NAV_END] = {"</nav", ">"},
    [HTML_SECTION_END] = {"</section", ">"},
    [HTML_HEADER_END] = {"</header", ">"},
    [HTML_FOOTER_END] = {"</footer", ">"},
    [HTML_ARTICLE_END] = {"</article", ">"},
    [HTML_ASIDE_END] = {"</aside", ">"},
    [HTML_CANVAS_END] = {"</canvas", ">"},
    [HTML_VIDEO_END] = {"</video", ">"},
    [HTML_AUDIO_END] = {"</audio", ">"},
    [HTML_SOURCE_END] = {"</source", ">"},
    [HTML_TRACK_END] = {"</track", ">"},
    [HTML_EMBED_END] = {"</embed", ">"},
    [HTML_OBJECT_END] = {"</object", ">"},
    [HTML_PARAM_END] = {"</param", ">"},
    [HTML_BLOCKQUOTE_END] = {"</blockquote", ">"},
    [HTML_CITE_END] = {"</cite", ">"},
    [HTML_CODE_END] = {"</code", ">"},
    [HTML_PRE_END] = {"</pre", ">"},
    [HTML_OL_END] = {"</ol", ">"},
    [HTML_BR_END] = {"</br", ">"},
    [HTML_HR_END] = {"</hr", ">"},
    [HTML_B_END] = {"</b", ">"},
    [HTML_I_END] = {"</i", ">"},
    [HTML_U_END] = {"</u", ">"},
    [HTML_SMALL_END] = {"</small", ">"},
    [HTML_SUB_END] = {"</sub", ">"},
    [HTML_SUP_END] = {"</sup", ">"},
    [HTML_INS_END] = {"</ins", ">"},
    [HTML_DEL_END] = {"</del", ">"},
    [HTML_MARK_END] = {"</mark", ">"},
    [HTML_Q_END] = {"</q", ">"},
    [HTML_DATA_END] = {"</data", ">"},
    [HTML_TIME_END] = {"</time", ">"},
    [HTML_OUTPUT_END] = {"</output", ">"},
    [HTML_PROGRESS_END] = {"</progress", ">"},
    [HTML_METER_END] = {"</meter", ">"},

    [HTML_END] = {"</", ">"},
    [HTML_UNKNOWN] = {"<", ">"}
};

CleksWhitespace html_whitespaces[] = {' ', '\n'};

CleksConfig html_config = { 
    .fields = html_fields,
    .field_count = CLEKS_ARR_LEN(html_fields),
    .whitespaces = html_whitespaces,
    .whitespace_count = CLEKS_ARR_LEN(html_whitespaces)
};